name: Build and Release

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm mtools

      - name: Build Base OS
        run: |
          make all
          cp out/flowop.img out/flowop_base.img

      - name: Build Demo OS
        run: |
          make app
          ./copyToIMG.sh
          mv out/flowop.img out/flowop_demo.img
          mv out/flowop_base.img out/flowop.img

      - name: Generate Release Tag
        id: tag
        run: echo "TAG_NAME=FLOWOP_$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: |
            out/flowop.img
            out/flowop_demo.img
